version: '3.1'

services:
  wiki:
    container_name: "wiki-web"
    build:
      context: ./wiki
    image: niaotuobang-wiki
    volumes:
      - ./wiki:/root/wiki
    restart: always
    networks:
      - wiki-net

  mysql:
    container_name: "wiki-mysql"
    image:  mysql:8.0.21
    volumes:
      - ./run/mysql/logs:/logs/:rw
      - ./run/mysql/data:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: wiki
      MYSQL_DATABASE: wiki
    restart: always
    networks:
        - wiki-net

  nginx:
    container_name: "wiki-nginx"
    image: nginx:stable
    ports:
      - "7780:80"
      - "7443:443"
    volumes:
      - .:/var/www/html/:rw
      - ./run/nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./run/nginx/logs:/var/log/nginx/:rw
    restart: always
    networks:
      - wiki-net

networks:
  wiki-net:
    external: true
